# Generated by Django 3.2.12 on 2022-03-13 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('file_app03', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='remark',
        ),
        migrations.RemoveField(
            model_name='file',
            name='timestamp',
        ),
    ]
